export const INIT_RESLIST = 'INIT_RESLIST';
export const INIT_HTML_DETAIL = 'INIT_HTML_DETAIL';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_LOGIN_MASK = 'SET_LOGIN_MASK';
export const SET_LOGIN_FAIL = 'SET_LOGIN_FAIL';
export const SET_REGISTER_FAIL = 'SET_REGISTER_FAIL';

export const LOADING = 'LOADING';


//评论
export const GET_COMMENT_LIST = 'GET_COMMENT_LIST';
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS';



export const RIGHT_RECOMMEND = 'RIGHT_RECOMMEND';
export const RIGHT_READYRANK = 'RIGHT_READYRANK';

