export const INIT_RESLIST = 'INIT_RESLIST';
export const INIT_HTML_DETAIL = 'INIT_HTML_DETAIL';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_LOGIN_MASK = 'SET_LOGIN_MASK';
export const SET_LOGIN_FAIL = 'SET_LOGIN_FAIL';
export const SET_REGISTER_FAIL = 'SET_REGISTER_FAIL';

//菜单
export const INIT_MENU = 'INIT_MENU';

export const RES_LOADING = 'RES_LOADING';
export const RECOMMED_LOADING = 'RECOMMED_LOADING'
export const READYRANK_LOADING = 'READYRANK_LOADING'


//评论
export const GET_COMMENT_LIST = 'GET_COMMENT_LIST';
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS';

export const GET_COMMUNITY_LIST = 'GET_COMMUNITY_LIST';
export const GET_COMMUNITYARTICLE_LIST = 'GET_COMMUNITYARTICLE_LIST';



export const RIGHT_RECOMMEND = 'RIGHT_RECOMMEND';
export const RIGHT_READYRANK = 'RIGHT_READYRANK';

